# Set platform to 15.5
platform :ios, '15.5'

# Load the Flutter podhelper script which defines necessary helper methods
flutter_ios_podfile_path = File.expand_path(File.join('..', 'Flutter', 'podhelper.rb'), __FILE__)
require flutter_ios_podfile_path

flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
    end
  end
end
